# -*- coding: utf-8 -*-
"""python

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LhTlggB5APzXaiwhqmGzrImHmJyZbCNn

# Your First AI application

Going forward, AI algorithms will be incorporated into more and more everyday applications. For example, you might want to include an image classifier in a smart phone app. To do this, you'd use a deep learning model trained on hundreds of thousands of images as part of the overall application architecture. A large part of software development in the future will be using these types of models as common parts of applications.

In this project, you'll train an image classifier to recognize different species of flowers. You can imagine using something like this in a phone app that tells you the name of the flower your camera is looking at. In practice you'd train this classifier, then export it for use in your application. We'll be using [this dataset](http://www.robots.ox.ac.uk/~vgg/data/flowers/102/index.html) from Oxford of 102 flower categories, you can see a few examples below.

<img src='assets/Flowers.png' width=500px>

The project is broken down into multiple steps:

* Load the image dataset and create a pipeline.
* Build and Train an image classifier on this dataset.
* Use your trained model to perform inference on flower images.

We'll lead you through each part which you'll implement in Python.

When you've completed this project, you'll have an application that can be trained on any set of labeled images. Here your network will be learning about flowers and end up as a command line application. But, what you do with your new skills depends on your imagination and effort in building a dataset. For example, imagine an app where you take a picture of a car, it tells you what the make and model is, then looks up information about it. Go build your own dataset and make something new.

## Import Resources
"""

# Done: Make all necessary imports.
import numpy as np
import tensorflow as tf
# Set the seed for NumPy
np.random.seed(42)
# Set the seed for TensorFlow
tf.random.set_seed(42)

import os, glob
import matplotlib.pyplot as plt
import numpy as np
import PIL
import tensorflow as tf
from tensorflow.keras.utils import load_img, img_to_array, array_to_img
from tensorflow.keras import layers, models
from tensorflow.keras.utils import to_categorical


import pandas as pd
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.datasets import mnist
from tensorflow.keras.layers import Conv2D, Dense, Flatten, MaxPooling2D
from tensorflow.keras.models import Sequential
import warnings

# Suppress all warnings
warnings.filterwarnings("ignore")

"""## Load the Dataset

Here you'll use `tensorflow_datasets` to load the [Oxford Flowers 102 dataset](https://www.tensorflow.org/datasets/catalog/oxford_flowers102). This dataset has 3 splits: `'train'`, `'test'`, and `'validation'`.  You'll also need to make sure the training data is normalized and resized to 224x224 pixels as required by the pre-trained networks.

The validation and testing sets are used to measure the model's performance on data it hasn't seen yet, but you'll still need to normalize and resize the images to the appropriate size.
"""

# done: Load the dataset with TensorFlow Datasets.

import tensorflow_datasets as tfds

# Load the "oxford_flowers102" dataset
dataset, info = tfds.load("oxford_flowers102", with_info=True, as_supervised=True)

# done: Create a training set, a validation set and a test set.

train_dataset,validation_dataset, test_dataset = dataset['train'],dataset['validation'],dataset['test']

def preprocess_image(image, label):
    # Resize to 224x224 pixels
    image = tf.image.resize(image, [224, 224])
    # Normalize to [0, 1]
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

# Apply the preprocessing to each dataset
train_dataset = train_dataset.map(preprocess_image)
validation_dataset = validation_dataset.map(preprocess_image)
test_dataset = test_dataset.map(preprocess_image)

# Optionally, you can batch the dataset for training
batch_size = 32
train_dataset = train_dataset.batch(batch_size)
validation_dataset = validation_dataset.batch(batch_size)
test_dataset = test_dataset.batch(batch_size)

# Print dataset info
print(info)

"""## Explore the Dataset"""

# TODO: Get the number of examples in each set from the dataset info.
num_train_examples = info.splits['train'].num_examples
num_validation_examples = info.splits['validation'].num_examples
num_test_examples = info.splits['test'].num_examples

print(f"Number of training examples: {num_train_examples}")
print(f"Number of validation examples: {num_validation_examples}")
print(f"Number of test examples: {num_test_examples}")

# TODO: Get the number of classes in the dataset from the dataset info.

# Get the number of classes in the dataset from the dataset info
num_classes = info.features['label'].num_classes

print(f"Number of classes: {num_classes}")

# TODO: Print the shape and corresponding label of 3 images in the training set.
for image, label in train_dataset.take(3):  # Take 3 examples from the dataset
    print(f"Image shape: {image.shape}, Label: {label.numpy()}")

# TODO: Plot 1 image from the training set. Set the title
# of the plot to the corresponding image label.
def plot_one_image_from_batch(dataset):
    for images, labels in dataset.take(1):
        image = images[0].numpy()
        label = labels[0].numpy()

        plt.imshow(image)
        plt.axis('off')
        plt.show()

plot_one_image_from_batch(train_dataset)

"""### Label Mapping

You'll also need to load in a mapping from label to category name. You can find this in the file `label_map.json`. It's a JSON object which you can read in with the [`json` module](https://docs.python.org/3.7/library/json.html). This will give you a dictionary mapping the integer coded labels to the actual names of the flowers.
"""

import json

with open('label_map.json', 'r') as f:
    class_names= json.load(f)

def plot_one_image_from_batch(dataset):
    for images, labels in dataset.take(1):
        image = images[0].numpy()
        label = labels[0].numpy()

        class_names=class_names.get(str(label), 'Unknown')

        plt.imshow(image)
        plt.title(class_name)  # Set the title to the class name
        plt.axis('off')  # Hide axis
        plt.show()

# Plot one image from the training dataset
plot_one_image_from_batch(train_dataset)

"""## Create Pipeline"""

batch_size

# done: Create a pipeline for each set.


train_pipeline = (train_dataset
                  .map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
                  .unbatch()
                  .batch(batch_size)
                  .prefetch(buffer_size=tf.data.AUTOTUNE))

validation_pipeline = (validation_dataset
                       .map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
                       .unbatch()
                       .batch(batch_size)
                       .prefetch(buffer_size=tf.data.AUTOTUNE))

test_pipeline = (test_dataset
                 .map(preprocess_image, num_parallel_calls=tf.data.AUTOTUNE)
                 .unbatch()
                 .batch(batch_size)
                 .prefetch(buffer_size=tf.data.AUTOTUNE))

test_pipeline

"""# Build and Train the Classifier

Now that the data is ready, it's time to build and train the classifier. You should use the MobileNet pre-trained model from TensorFlow Hub to get the image features. Build and train a new feed-forward classifier using those features.

We're going to leave this part up to you. If you want to talk through it with someone, chat with your fellow students!

Refer to the rubric for guidance on successfully completing this section. Things you'll need to do:

* Load the MobileNet pre-trained network from TensorFlow Hub.
* Define a new, untrained feed-forward network as a classifier.
* Train the classifier.
* Plot the loss and accuracy values achieved during training for the training and validation set.
* Save your trained model as a Keras model.

We've left a cell open for you below, but use as many as you need. Our advice is to break the problem up into smaller parts you can run separately. Check that each part is doing what you expect, then move on to the next. You'll likely find that as you work through each part, you'll need to go back and modify your previous code. This is totally normal!

When training make sure you're updating only the weights of the feed-forward network. You should be able to get the validation accuracy above 70% if you build everything right.

**Note for Workspace users:** One important tip if you're using the workspace to run your code: To avoid having your workspace disconnect during the long-running tasks in this notebook, please read in the earlier page in this lesson called Intro to GPU Workspaces about Keeping Your Session Active. You'll want to include code from the workspace_utils.py module. Also, If your model is over 1 GB when saved as a checkpoint, there might be issues with saving backups in your workspace. If your saved checkpoint is larger than 1 GB (you can open a terminal and check with `ls -lh`), you should reduce the size of your hidden layers and train again.
"""

# Done: Build and train your network.
import tensorflow_hub as hub

# Load the MobileNet model from TensorFlow Hub
mobilenet_url = "https://tfhub.dev/google/tf2-preview/mobilenet_v2/feature_vector/4"
feature_extractor = hub.KerasLayer(mobilenet_url, input_shape=(224, 224, 3), trainable=False)

# Build the model
model = tf.keras.Sequential([
    feature_extractor,  # Output shape is (None, 1280)

    # Add hidden (dense) layers
    tf.keras.layers.Dense(512, activation='relu'),
    tf.keras.layers.Dropout(0.5),  # Add dropout for regularization

    tf.keras.layers.Dense(256, activation='relu'),
    tf.keras.layers.Dropout(0.5),

    tf.keras.layers.Dense(102, activation='softmax')  # 102 classes for the flowers
])

model.compile(
    optimizer=tf.keras.optimizers.Adam(),
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_pipeline,
    validation_data=validation_pipeline,
    epochs=10
)

# TODO: Plot the loss and accuracy values achieved during training for the training and validation set.

# Plotting the loss
plt.figure(figsize=(12, 6))

# Training and validation loss
plt.subplot(1, 2, 1)
plt.plot(history.history['loss'], label='Training Loss')
plt.plot(history.history['val_loss'], label='Validation Loss')
plt.title('Training and Validation Loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()

# Training and validation accuracy
plt.subplot(1, 2, 2)
plt.plot(history.history['accuracy'], label='Training Accuracy')
plt.plot(history.history['val_accuracy'], label='Validation Accuracy')
plt.title('Training and Validation Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Accuracy')
plt.legend()

# Show the plots
plt.show()

"""## Testing your Network

It's good practice to test your trained network on test data, images the network has never seen either in training or validation. This will give you a good estimate for the model's performance on completely new images. You should be able to reach around 70% accuracy on the test set if the model has been trained well.
"""

# TODO: Print the loss and accuracy values achieved on the entire test set.

test_loss, test_accuracy = model.evaluate(test_pipeline)

# Print the results
print(f"Test Loss: {test_loss}")
print(f"Test Accuracy: {test_accuracy}")

"""## Save the Model

Now that your network is trained, save the model so you can load it later for making inference. In the cell below save your model as a Keras model (*i.e.* save it as an HDF5 file).
"""

# TODO: Save your trained model as a Keras model.


model.save('flower_classifier_model.h5')

"""## Load the Keras Model

Load the Keras model you saved above.
"""

from tensorflow.keras.layers import Layer
import tensorflow_hub as hub
import tensorflow as tf

class KerasLayer(Layer):
    def __init__(self, handle, **kwargs):
        super(KerasLayer, self).__init__(**kwargs)
        self.handle = handle
        self.tf_hub_module = hub.KerasLayer(handle, trainable=False)

    def call(self, inputs):
        return self.tf_hub_module(inputs)

from tensorflow.keras.utils import custom_object_scope
from tensorflow.keras.models import load_model

# Load the model with the custom object scope
with custom_object_scope({'KerasLayer': KerasLayer}):
    model = load_model('flower_classifier_model.h5')
model.summary()

"""
When you encounter the ValueError: Unknown layer: 'KerasLayer' error,
 it usually means that the model you are trying to load includes custom layers or objects that are not part of the standard Keras library.
 In such cases, you need to take additional steps to handle these custom components properly.

 """

"""# Inference for Classification

Now you'll write a function that uses your trained network for inference. Write a function called `predict` that takes an image, a model, and then returns the top $K$ most likely class labels along with the probabilities. The function call should look like:

```python
probs, classes = predict(image_path, model, top_k)
```

If `top_k=5` the output of the `predict` function should be something like this:

```python
probs, classes = predict(image_path, model, 5)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

Your `predict` function should use `PIL` to load the image from the given `image_path`. You can use the [Image.open](https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.open) function to load the images. The `Image.open()` function returns an `Image` object. You can convert this `Image` object to a NumPy array by using the `np.asarray()` function.

The `predict` function will also need to handle pre-processing the input image such that it can be used by your model. We recommend you write a separate function called `process_image` that performs the pre-processing. You can then call the `process_image` function from the `predict` function.

### Image Pre-processing

The `process_image` function should take in an image (in the form of a NumPy array) and return an image in the form of a NumPy array with shape `(224, 224, 3)`.

First, you should convert your image into a TensorFlow Tensor and then resize it to the appropriate size using `tf.image.resize`.

Second, the pixel values of the input images are typically encoded as integers in the range 0-255, but the model expects the pixel values to be floats in the range 0-1. Therefore, you'll also need to normalize the pixel values.

Finally, convert your image back to a NumPy array using the `.numpy()` method.
"""

# TODO: Create the process_image function


def process_image(image_path):
    # Read the image file
    image = tf.io.read_file(image_path)

    # Decode the image as a JPEG file, this will give you a tensor of shape (height, width, channels)
    image = tf.image.decode_jpeg(image, channels=3)

    # Resize the image to 224x224 pixels as required by most CNN models
    image = tf.image.resize(image, [224, 224])

    # Normalize the pixel values to the range [0, 1]
    image = image / 255.0

    # Add a batch dimension, since the model expects batches of images
    image = tf.expand_dims(image, axis=0)
    return image

"""To check your `process_image` function we have provided 4 images in the `./test_images/` folder:

* cautleya_spicata.jpg
* hard-leaved_pocket_orchid.jpg
* orange_dahlia.jpg
* wild_pansy.jpg

The code below loads one of the above images using `PIL` and plots the original image alongside the image produced by your `process_image` function. If your `process_image` function works, the plotted image should be the correct size.
"""

from PIL import Image

image_path = './test_images/hard-leaved_pocket_orchid.jpg'
im = Image.open(image_path)
test_image = np.asarray(im)

processed_test_image = process_image(test_image)

fig, (ax1, ax2) = plt.subplots(figsize=(10,10), ncols=2)
ax1.imshow(test_image)
ax1.set_title('Original Image')
ax2.imshow(processed_test_image)
ax2.set_title('Processed Image')
plt.tight_layout()
plt.show()

"""Once you can get images in the correct format, it's time to write the `predict` function for making inference with your model.

### Inference

Remember, the `predict` function should take an image, a model, and then returns the top $K$ most likely class labels along with the probabilities. The function call should look like:

```python
probs, classes = predict(image_path, model, top_k)
```

If `top_k=5` the output of the `predict` function should be something like this:

```python
probs, classes = predict(image_path, model, 5)
print(probs)
print(classes)
> [ 0.01558163  0.01541934  0.01452626  0.01443549  0.01407339]
> ['70', '3', '45', '62', '55']
```

Your `predict` function should use `PIL` to load the image from the given `image_path`. You can use the [Image.open](https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.open) function to load the images. The `Image.open()` function returns an `Image` object. You can convert this `Image` object to a NumPy array by using the `np.asarray()` function.

**Note:** The image returned by the `process_image` function is a NumPy array with shape `(224, 224, 3)` but the model expects the input images to be of shape `(1, 224, 224, 3)`. This extra dimension represents the batch size. We suggest you use the `np.expand_dims()` function to add the extra dimension.
"""

# TODO: Create the predict function

"""# Sanity Check

It's always good to check the predictions made by your model to make sure they are correct. To check your predictions we have provided 4 images in the `./test_images/` folder:

* cautleya_spicata.jpg
* hard-leaved_pocket_orchid.jpg
* orange_dahlia.jpg
* wild_pansy.jpg

In the cell below use `matplotlib` to plot the input image alongside the probabilities for the top 5 classes predicted by your model. Plot the probabilities as a bar graph. The plot should look like this:

<img src='assets/inference_example.png' width=600px>

You can convert from the class integer labels to actual flower names using `class_names`.
"""

# TODO: Plot the input image along with the top 5 classes